In [ ]:
!pip install beautifulsoup4
!pip install requests
!pip install pandas
!pip install lxml

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (4.11.2)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4) (2.4.1)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (2.27.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests) (3.4)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests) (2.0.12)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.22.4)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2022.7.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: lxml in /usr/local/lib/python3.10/dist-packages (4.9.2)

In [ ]:
# Import libraries
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [ ]:
max = 100
total = [*range(1,max)]
total
inputurl = "https://www.idnfinancials.com/company/industry/food-and-beverages-42"

# Create an URL object
for pagenum in range(1,max):
  url = inputurl + '/' + str(pagenum)
  code = url.split('/')[5].split('-')[0]
  # Create object page
  page = requests.get(url)
  soup = BeautifulSoup(page.text, 'lxml')
  # Obtain information from tag <table>
  table1 = soup.find('div', id="table-companies")
  # Obtain every title of columns with tag <th>
  headers = []
  url_list = []
  try:
    for i in table1.find_all('a', class_ = "table-sorter"):
      title = i.text
      headers.append(title)
    # Create a dataframe
    mydata1 = pd.DataFrame(columns = headers)
    # Create a for loop to fill mydata1
    for j in table1.find_all(class_ = "table-row")[1:]:
      row_data = j.find_all("div")
      row = [i.text for i in row_data]
      length = len(mydata1)
      mydata1.loc[length] = row
    table1 = soup.find('div', id="table-companies")
    for y in table1.find_all(class_ = "table-row")[1:]:
      for a in y.find_all('a', href=True):
        url_list.append(a['href'])
    
    mydata1['URL'] = url_list

    mydata1['Company']=mydata1['Company'].str[1:5]
    # Export to csv
    namecsv = 'companylist'+ str(pagenum) + '.csv'
    mydata1.to_csv(namecsv, index=False)
  except:
    print("fail")
    total.remove(pagenum)
max_merge = total[-1]
merge_csv_list = list()

newdf_append = pd.DataFrame()

for z in range(1,max_merge+1):
  merge_name_csv = 'companylist'+ str(z) + '.csv'
  merge_csv_list.append(merge_name_csv)

sector = code

df_csv_concat_all = pd.concat([pd.read_csv(file) for file in merge_csv_list], ignore_index=True)
df_csv_concat_all.to_csv("data-"+ sector +".csv")

In [ ]:
print(len(df_csv_concat_all['URL']))

47

In [ ]:
df_csv_concat_all

,Company,Price,Change,EPS,PER,Market Cap.(Million IDR),URL
0,ICBP,10.875,"+150 (+1,38%)",339,32.0,"128.572.446,00",https://www.idnfinancials.com/icbp/pt-indofood...
1,MYOR,2.640,"+60 (+2,27%)",33,80.0,"60.368.492,00",https://www.idnfinancials.com/myor/pt-mayora-i...
2,INDF,6.700,"+175 (+2,61%)",438,15.0,"60.365.459,00",https://www.idnfinancials.com/indf/pt-indofood...
3,CMRY,4.380,"-60 (-1,00%)",37,118.0,"34.277.817,00",https://www.idnfinancials.com/cmry/pt-cisarua-...
4,MLBI,8.950,"-50 (-1,00%)",97,92.0,"18.752.301,00",https://www.idnfinancials.com/mlbi/pt-multi-bi...
5,GOOD,468.000,"-4 (-1,00%)",4,109.0,"16.949.131,00",https://www.idnfinancials.com/good/pt-garudafo...
6,PANI,1.175,"+45 (+4,00%)",4,305.0,"16.506.601,00",https://www.idnfinancials.com/pani/pt-pratama-...
7,ULTJ,1.470,"+10 (+1,00%)",34,43.0,"15.389.335,00",https://www.idnfinancials.com/ultj/pt-ultra-ja...
8,ROTI,1.325,"+30 (+2,00%)",75,18.0,"7.727.877,00",https://www.idnfinancials.com/roti/pt-nippon-i...
9,DMND,805.000,"-5 (-0,62%)",29,28.0,"7.622.030,00",https://www.idnfinancials.com/dmnd/pt-diamond-...
10,CLEO,525.000,"+5 (+1,00%)",16,33.0,"6.338.800,00",https://www.idnfinancials.com/cleo/pt-sariguna...
11,ADES,8.025,"+75 (+1,00%)",408,20.0,"4.882.364,00",https://www.idnfinancials.com/ades/pt-akasha-w...
12,DLTA,3.850,"+10 (+0,26%)",227,17.0,"3.146.738,00",https://www.idnfinancials.com/dlta/pt-delta-dj...
13,PSGO,140.000,"-1 (-1,00%)",7,19.0,"2.620.150,00",https://www.idnfinancials.com/psgo/pt-palma-se...
14,BTEK,50.000,0 (0%),-3,-17.0,"2.313.875,00",https://www.idnfinancials.com/btek/pt-bumi-tek...
15,IBOS,262.000,"-2 (-1,00%)",0,535.0,"2.089.810,00",https://www.idnfinancials.com/ibos/pt-indo-bog...
16,CAMP,344.000,"-2 (-0,58%)",18,19.0,"2.024.440,00",https://www.idnfinancials.com/camp/pt-campina-...
17,KEJU,1.260,"+5 (+0,40%)",76,17.0,"1.897.500,00",https://www.idnfinancials.com/keju/pt-mulia-bo...
18,TRGU,212.000,"+2 (+1,00%)",7,31.0,"1.700.318,00",https://www.idnfinancials.com/trgu/pt-cerestar...
19,SKLT,2.400,"+70 (+3,00%)",67,36.0,"1.535.515,00",https://www.idnfinancials.com/sklt/pt-sekar-la...
20,WINE,438.000,"+107 (+24,00%)",10,42.0,"1.476.950,00",https://www.idnfinancials.com/wine/pt-hatten-b...
21,BEER,346.000,"+2 (+1,00%)",3,111.0,"1.392.000,00",https://www.idnfinancials.com/beer/pt-jobubu-j...
22,CEKA,2.010,"-10 (-0,50%)",119,17.0,"1.195.950,00",https://www.idnfinancials.com/ceka/pt-wilmar-c...
23,BUDI,216.000,"+8 (+4,00%)",14,15.0,"1.007.776,00",https://www.idnfinancials.com/budi/pt-budi-sta...
24,HOKI,89.000,"-1 (-1,00%)",0,494.0,"851.642,00",https://www.idnfinancials.com/hoki/pt-buyung-p...
25,PMMP,288.000,"+2 (+1,00%)",0,90.0,"682.370,00",https://www.idnfinancials.com/pmmp/pt-panca-mi...
26,WMUU,50.000,0 (0%),-1,-71.0,"647.060,00",https://www.idnfinancials.com/wmuu/pt-widodo-m...
27,AISA,144.000,"-3 (-2,00%)",-4,-34.0,"536.607,00",https://www.idnfinancials.com/aisa/pt-fks-food...
28,SKBM,312.000,"-20 (-6,00%)",29,11.0,"505.189,00",https://www.idnfinancials.com/skbm/pt-sekar-bu...
29,CRAB,226.000,"+4 (+1,77%)",2,146.0,"448.500,00",https://www.idnfinancials.com/crab/pt-toba-sur...
30,NAYZ,163.000,"-4 (-2,45%)",1,148.0,"405.450,00",https://www.idnfinancials.com/nayz/pt-hassana-...
31,GULA,298.000,"+14 (+4,70%)",3,101.0,"333.952,00",https://www.idnfinancials.com/gula/pt-aman-agr...
32,COCO,232.000,"+4 (+1,72%)",5,45.0,"210.008,00",https://www.idnfinancials.com/coco/pt-wahana-i...
33,TAYS,167.000,"-11 (-6,59%)",9,19.0,"171.432,00",https://www.idnfinancials.com/tays/pt-jaya-swa...
34,MGNA,50.000,0 (0%),-3,-14.0,"170.524,00",https://www.idnfinancials.com/mgna/pt-magna-in...
35,BOBA,144.000,"-1 (-0,69%)",8,18.0,"167.567,00",https://www.idnfinancials.com/boba/pt-formosa-...
36,ALTO,50.000,0 (0%),2,28.0,"109.593,00",https://www.idnfinancials.com/alto/pt-tri-bany...
37,ENZO,50.000,0 (0%),1,40.0,"108.128,00",https://www.idnfinancials.com/enzo/pt-morenzo-...
38,PSDN,53.000,"+1 (+2,00%)",-22,-2.0,"77.760,00",https://www.idnfinancials.com/psdn/pt-prasidha...
39,FOOD,106.000,"+3 (+3,00%)",-19,-5.0,"70.850,00",https://www.idnfinancials.com/food/pt-sentra-f...
40,NASI,82.000,"-5 (-6,00%)",2,46.0,"62.170,00",https://www.idnfinancials.com/nasi/pt-wahana-i...
41,AMMS,52.000,"-3 (-6,00%)",1,39.0,"58.801,00",https://www.idnfinancials.com/amms/pt-agung-me...
42,PCAR,50.000,0 (0%),3,17.0,"58.333,00",https://www.idnfinancials.com/pcar/pt-prima-ca...
43,IKAN,56.000,"+2 (+4,00%)",2,23.0,"48.333,00",https://www.idnfinancials.com/ikan/pt-era-mand...
44,SOUL,27.000,"+1 (+4,00%)",1.029.119,0.0,"30.310,00",https://www.idnfinancials.com/soul/pt-mitra-ti...
45,STTP,7.425,0 (0%),320,23.0,0,https://www.idnfinancials.com/sttp/pt-siantar-...
46,IIKP,50.000,0 (0%),-4,-13.0,0,https://www.idnfinancials.com/iikp/pt-inti-agr...

In [ ]:
counter = -1
for dd in df_csv_concat_all['URL']:
  counter = counter + 1
  max = 15
  total = [*range(1,max)]
  total
  
  try:
    print(str(dd)+"/dividend/")

    inputurl = str(dd)+"/dividend/"
    
    # Create an URL object
    for pagenum in range(1,max):
      url = inputurl + str(pagenum)
      code = url.split('/')[3]
      # Create object page
      page = requests.get(url)
      soup = BeautifulSoup(page.text, 'lxml')
      # Obtain information from tag <table>
      table1 = soup.find('table', id='table-dividend')
      # Obtain every title of columns with tag <th>
      try:
        headers = []
        for i in table1.find_all('th'):
          title = i.text
          headers.append(title)
        # Create a dataframe
        mydata3 = pd.DataFrame(columns = headers)
        # Create a for loop to fill mydata3
        for j in table1.find_all('tr')[1:]:
          row_data = j.find_all('td')
          row = [i.text for i in row_data]
          length = len(mydata3)
          mydata3.loc[length] = row
        # Drop and clearing unnecessary rows
        mydata3.drop('Bonus Shares', inplace=True, axis=1)
        # Drop and clearing unnecessary rows
        mydata3['Cash Dividend']=mydata3['Cash Dividend'].map(lambda x: x.rstrip('IDRUSD()'))
        mydata3['Cash Dividend']=mydata3['Cash Dividend'].astype(float)
        mydata3['Year']=mydata3['Year'].astype(int)
        # Export to csv
        namecsv = 'pure-dividend-'+ str(code)+ "-"+ str(pagenum) + '.csv'
        mydata3.to_csv(namecsv, index=False)
      except:
        total.remove(pagenum)

    max_merge = total[-1]
    merge_csv_list = list()

    newdf_append = pd.DataFrame()

    for z in range(1,max_merge+1):
      merge_name_csv = 'pure-dividend-'+ str(code)+ "-"+ str(z) + '.csv'
      merge_csv_list.append(merge_name_csv)

    df_csv_concat = pd.concat([pd.read_csv(file) for file in merge_csv_list], ignore_index=True)

    groupdatatotal = df_csv_concat.groupby('Year').sum()
    groupdatatotal = groupdatatotal.sort_values(by=['Year'], ascending = False)

    df_finalonly = df_csv_concat
    df_finalonly = df_finalonly[df_finalonly.Type == 'Final']
    df_finalonly_sum = df_finalonly.groupby('Year').sum()
    df_finalonly_sum = df_finalonly_sum.sort_values(by=['Year'], ascending = False)
    df_finalonly_sum.T
    df_finalonly_sum.to_csv("finalonly-total-data-"+ code +".csv")
  except:
    headers1 = ['Year', 'Cash Dividend']
    df_finalonly_sum = pd.DataFrame(columns = headers1)
    df_finalonly_sum.loc[0] = [0, 0]
    df_finalonly_sum = df_finalonly_sum.groupby('Year').sum()
    df_finalonly_sum = df_finalonly_sum.sort_values(by=['Year'], ascending = False)
    df_finalonly_sum.T
    df_finalonly_sum.to_csv("finalonly-total-data-"+ code +".csv")
    pass

https://www.idnfinancials.com/icbp/pt-indofood-cbp-sukses-makmur-tbk/dividend/

<ipython-input-7-3ccca479fd3f>:59: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  groupdatatotal = df_csv_concat.groupby('Year').sum()
<ipython-input-7-3ccca479fd3f>:64: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_finalonly_sum = df_finalonly.groupby('Year').sum()

https://www.idnfinancials.com/myor/pt-mayora-indah-tbk/dividend/

<ipython-input-7-3ccca479fd3f>:59: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  groupdatatotal = df_csv_concat.groupby('Year').sum()
<ipython-input-7-3ccca479fd3f>:64: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_finalonly_sum = df_finalonly.groupby('Year').sum()

https://www.idnfinancials.com/indf/pt-indofood-sukses-makmur-tbk/dividend/

<ipython-input-7-3ccca479fd3f>:59: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  groupdatatotal = df_csv_concat.groupby('Year').sum()
<ipython-input-7-3ccca479fd3f>:64: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_finalonly_sum = df_finalonly.groupby('Year').sum()

https://www.idnfinancials.com/cmry/pt-cisarua-mountain-dairy-tbk/dividend/
https://www.idnfinancials.com/mlbi/pt-multi-bintang-indonesia-tbk/dividend/

<ipython-input-7-3ccca479fd3f>:59: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  groupdatatotal = df_csv_concat.groupby('Year').sum()
<ipython-input-7-3ccca479fd3f>:64: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_finalonly_sum = df_finalonly.groupby('Year').sum()

https://www.idnfinancials.com/good/pt-garudafood-putra-putri-jaya-tbk/dividend/
https://www.idnfinancials.com/pani/pt-pratama-abadi-nusa-industri-tbk/dividend/
https://www.idnfinancials.com/ultj/pt-ultra-jaya-milk-industry-trading-company-tbk/dividend/

<ipython-input-7-3ccca479fd3f>:59: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  groupdatatotal = df_csv_concat.groupby('Year').sum()
<ipython-input-7-3ccca479fd3f>:64: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_finalonly_sum = df_finalonly.groupby('Year').sum()

https://www.idnfinancials.com/roti/pt-nippon-indosari-corpindo-tbk/dividend/
https://www.idnfinancials.com/dmnd/pt-diamond-food-indonesia-tbk/dividend/
https://www.idnfinancials.com/cleo/pt-sariguna-primatirta-tbk/dividend/

<ipython-input-7-3ccca479fd3f>:59: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  groupdatatotal = df_csv_concat.groupby('Year').sum()
<ipython-input-7-3ccca479fd3f>:64: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_finalonly_sum = df_finalonly.groupby('Year').sum()

https://www.idnfinancials.com/ades/pt-akasha-wira-international-tbk/dividend/

<ipython-input-7-3ccca479fd3f>:59: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  groupdatatotal = df_csv_concat.groupby('Year').sum()
<ipython-input-7-3ccca479fd3f>:64: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_finalonly_sum = df_finalonly.groupby('Year').sum()

https://www.idnfinancials.com/dlta/pt-delta-djakarta-tbk/dividend/

<ipython-input-7-3ccca479fd3f>:59: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  groupdatatotal = df_csv_concat.groupby('Year').sum()
<ipython-input-7-3ccca479fd3f>:64: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_finalonly_sum = df_finalonly.groupby('Year').sum()

https://www.idnfinancials.com/psgo/pt-palma-serasih-tbk/dividend/
https://www.idnfinancials.com/btek/pt-bumi-teknokultura-unggul-tbk/dividend/

<ipython-input-7-3ccca479fd3f>:59: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  groupdatatotal = df_csv_concat.groupby('Year').sum()
<ipython-input-7-3ccca479fd3f>:64: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_finalonly_sum = df_finalonly.groupby('Year').sum()

https://www.idnfinancials.com/ibos/pt-indo-boga-sukses-tbk/dividend/
https://www.idnfinancials.com/camp/pt-campina-ice-cream-industry-tbk/dividend/

<ipython-input-7-3ccca479fd3f>:59: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  groupdatatotal = df_csv_concat.groupby('Year').sum()
<ipython-input-7-3ccca479fd3f>:64: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_finalonly_sum = df_finalonly.groupby('Year').sum()

https://www.idnfinancials.com/keju/pt-mulia-boga-raya-tbk/dividend/
https://www.idnfinancials.com/trgu/pt-cerestar-indonesia-tbk/dividend/
https://www.idnfinancials.com/sklt/pt-sekar-laut-tbk/dividend/

<ipython-input-7-3ccca479fd3f>:59: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  groupdatatotal = df_csv_concat.groupby('Year').sum()
<ipython-input-7-3ccca479fd3f>:64: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_finalonly_sum = df_finalonly.groupby('Year').sum()

https://www.idnfinancials.com/wine/pt-hatten-bali-tbk/dividend/
https://www.idnfinancials.com/beer/pt-jobubu-jarum-minahasa-tbk/dividend/
https://www.idnfinancials.com/ceka/pt-wilmar-cahaya-indonesia-tbk/dividend/

<ipython-input-7-3ccca479fd3f>:59: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  groupdatatotal = df_csv_concat.groupby('Year').sum()
<ipython-input-7-3ccca479fd3f>:64: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_finalonly_sum = df_finalonly.groupby('Year').sum()

https://www.idnfinancials.com/budi/pt-budi-starch-sweetener-tbk/dividend/

<ipython-input-7-3ccca479fd3f>:59: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  groupdatatotal = df_csv_concat.groupby('Year').sum()
<ipython-input-7-3ccca479fd3f>:64: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_finalonly_sum = df_finalonly.groupby('Year').sum()

https://www.idnfinancials.com/hoki/pt-buyung-poetra-sembada-tbk/dividend/

<ipython-input-7-3ccca479fd3f>:59: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  groupdatatotal = df_csv_concat.groupby('Year').sum()
<ipython-input-7-3ccca479fd3f>:64: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_finalonly_sum = df_finalonly.groupby('Year').sum()

https://www.idnfinancials.com/pmmp/pt-panca-mitra-multiperdana-tbk/dividend/

<ipython-input-7-3ccca479fd3f>:59: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  groupdatatotal = df_csv_concat.groupby('Year').sum()
<ipython-input-7-3ccca479fd3f>:64: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_finalonly_sum = df_finalonly.groupby('Year').sum()

https://www.idnfinancials.com/wmuu/pt-widodo-makmur-unggas-tbk/dividend/

<ipython-input-7-3ccca479fd3f>:59: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  groupdatatotal = df_csv_concat.groupby('Year').sum()
<ipython-input-7-3ccca479fd3f>:64: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_finalonly_sum = df_finalonly.groupby('Year').sum()

https://www.idnfinancials.com/aisa/pt-fks-food-sejahtera-tbk/dividend/

<ipython-input-7-3ccca479fd3f>:59: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  groupdatatotal = df_csv_concat.groupby('Year').sum()
<ipython-input-7-3ccca479fd3f>:64: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_finalonly_sum = df_finalonly.groupby('Year').sum()

https://www.idnfinancials.com/skbm/pt-sekar-bumi-tbk/dividend/

<ipython-input-7-3ccca479fd3f>:59: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  groupdatatotal = df_csv_concat.groupby('Year').sum()
<ipython-input-7-3ccca479fd3f>:64: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_finalonly_sum = df_finalonly.groupby('Year').sum()

https://www.idnfinancials.com/crab/pt-toba-surimi-industries-tbk/dividend/
https://www.idnfinancials.com/nayz/pt-hassana-boga-sejahtera-tbk/dividend/
https://www.idnfinancials.com/gula/pt-aman-agrindo-tbk/dividend/
https://www.idnfinancials.com/coco/pt-wahana-interfood-nusantara-tbk/dividend/
https://www.idnfinancials.com/tays/pt-jaya-swarasa-agung-tbk/dividend/
https://www.idnfinancials.com/mgna/pt-magna-investama-mandiri-tbk/dividend/
https://www.idnfinancials.com/boba/pt-formosa-ingredient-factory-tbk/dividend/

<ipython-input-7-3ccca479fd3f>:59: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  groupdatatotal = df_csv_concat.groupby('Year').sum()
<ipython-input-7-3ccca479fd3f>:64: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_finalonly_sum = df_finalonly.groupby('Year').sum()

https://www.idnfinancials.com/alto/pt-tri-banyan-tirta-tbk/dividend/
https://www.idnfinancials.com/enzo/pt-morenzo-abadi-perkasa-tbk/dividend/
https://www.idnfinancials.com/psdn/pt-prasidha-aneka-niaga-tbk/dividend/

<ipython-input-7-3ccca479fd3f>:59: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  groupdatatotal = df_csv_concat.groupby('Year').sum()
<ipython-input-7-3ccca479fd3f>:64: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_finalonly_sum = df_finalonly.groupby('Year').sum()

https://www.idnfinancials.com/food/pt-sentra-food-indonesia-tbk/dividend/
https://www.idnfinancials.com/nasi/pt-wahana-inti-makmur-tbk/dividend/
https://www.idnfinancials.com/amms/pt-agung-menjangan-mas-tbk/dividend/
https://www.idnfinancials.com/pcar/pt-prima-cakrawala-abadi-tbk/dividend/
https://www.idnfinancials.com/ikan/pt-era-mandiri-cemerlang-tbk/dividend/
https://www.idnfinancials.com/soul/pt-mitra-tirta-buwana-tbk/dividend/
https://www.idnfinancials.com/sttp/pt-siantar-top-tbk/dividend/

<ipython-input-7-3ccca479fd3f>:59: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  groupdatatotal = df_csv_concat.groupby('Year').sum()
<ipython-input-7-3ccca479fd3f>:64: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_finalonly_sum = df_finalonly.groupby('Year').sum()

https://www.idnfinancials.com/iikp/pt-inti-agri-resources-tbk/dividend/

<ipython-input-7-3ccca479fd3f>:59: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  groupdatatotal = df_csv_concat.groupby('Year').sum()
<ipython-input-7-3ccca479fd3f>:64: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_finalonly_sum = df_finalonly.groupby('Year').sum()

In [ ]:
df_csv_concat_all[2022] = 0
df_csv_concat_all[2021] = 0
df_csv_concat_all[2020] = 0
df_csv_concat_all[2019] = 0
df_csv_concat_all[2018] = 0
df_csv_concat_all[2017] = 0
df_csv_concat_all[2016] = 0
df_csv_concat_all[2015] = 0
df_csv_concat_all[2014] = 0
df_csv_concat_all[2013] = 0
df_csv_concat_all[2012] = 0
df_csv_concat_all[2011] = 0
df_csv_concat_all[2010] = 0
df_csv_concat_all[2009] = 0
df_csv_concat_all[2008] = 0
df_csv_concat_all[2007] = 0
df_csv_concat_all[2006] = 0
df_csv_concat_all[2005] = 0


for aa in range(0,len(df_csv_concat_all['URL'])):
  newdata = pd.read_csv(str("finalonly-total-data-"+ str(df_csv_concat_all['Company'][aa]).lower()) + ".csv").T
  newdata.columns = newdata.iloc[0].astype(int)
  newdata = newdata.drop('Year')
  try:
    df_csv_concat_all[2022].iloc[aa] = newdata[2022]
  except:
    pass
  try:
    df_csv_concat_all[2021].iloc[aa] = newdata[2021]
  except:
    pass
  try:
    df_csv_concat_all[2020].iloc[aa] = newdata[2020]
  except:
    pass
  try:
    df_csv_concat_all[2019].iloc[aa] = newdata[2019]
  except:
    pass
  try:
    df_csv_concat_all[2018].iloc[aa] = newdata[2018]
  except:
    pass
  try:
    df_csv_concat_all[2017].iloc[aa] = newdata[2017]
  except:
    pass
  try:
    df_csv_concat_all[2016].iloc[aa] = newdata[2016]
  except:
    pass
  try:
    df_csv_concat_all[2015].iloc[aa] = newdata[2015]
  except:
    pass
  try:
    df_csv_concat_all[2014].iloc[aa] = newdata[2014]
  except:
    pass
  try:
    df_csv_concat_all[2013].iloc[aa] = newdata[2013]
  except:
    pass
  try:
    df_csv_concat_all[2012].iloc[aa] = newdata[2012]
  except:
    pass
  try:
    df_csv_concat_all[2011].iloc[aa] = newdata[2011]
  except:
    pass
  try:
    df_csv_concat_all[2010].iloc[aa] = newdata[2010]
  except:
    pass
  try:
    df_csv_concat_all[2009].iloc[aa] = newdata[2009]
  except:
    pass
  try:
    df_csv_concat_all[2008].iloc[aa] = newdata[2008]
  except:
    pass
  try:
    df_csv_concat_all[2007].iloc[aa] = newdata[2007]
  except:
    pass
  try:
    df_csv_concat_all[2006].iloc[aa] = newdata[2006]
  except:
    pass
  try:
    df_csv_concat_all[2005].iloc[aa] = newdata[2005]
  except:
    pass

<ipython-input-8-47fdbec520c1>:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2021].iloc[aa] = newdata[2021]
<ipython-input-8-47fdbec520c1>:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2020].iloc[aa] = newdata[2020]
<ipython-input-8-47fdbec520c1>:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2019].iloc[aa] = newdata[2019]
<ipython-input-8-47fdbec520c1>:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2018].iloc[aa] = newdata[2018]
<ipython-input-8-47fdbec520c1>:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2017].iloc[aa] = newdata[2017]
<ipython-input-8-47fdbec520c1>:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2016].iloc[aa] = newdata[2016]
<ipython-input-8-47fdbec520c1>:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2015].iloc[aa] = newdata[2015]
<ipython-input-8-47fdbec520c1>:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2014].iloc[aa] = newdata[2014]
<ipython-input-8-47fdbec520c1>:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2013].iloc[aa] = newdata[2013]
<ipython-input-8-47fdbec520c1>:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2012].iloc[aa] = newdata[2012]
<ipython-input-8-47fdbec520c1>:70: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2011].iloc[aa] = newdata[2011]
<ipython-input-8-47fdbec520c1>:74: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2010].iloc[aa] = newdata[2010]
<ipython-input-8-47fdbec520c1>:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2021].iloc[aa] = newdata[2021]
<ipython-input-8-47fdbec520c1>:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2020].iloc[aa] = newdata[2020]
<ipython-input-8-47fdbec520c1>:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2019].iloc[aa] = newdata[2019]
<ipython-input-8-47fdbec520c1>:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2018].iloc[aa] = newdata[2018]
<ipython-input-8-47fdbec520c1>:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2017].iloc[aa] = newdata[2017]
<ipython-input-8-47fdbec520c1>:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2016].iloc[aa] = newdata[2016]
<ipython-input-8-47fdbec520c1>:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2015].iloc[aa] = newdata[2015]
<ipython-input-8-47fdbec520c1>:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2014].iloc[aa] = newdata[2014]
<ipython-input-8-47fdbec520c1>:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2013].iloc[aa] = newdata[2013]
<ipython-input-8-47fdbec520c1>:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2012].iloc[aa] = newdata[2012]
<ipython-input-8-47fdbec520c1>:70: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2011].iloc[aa] = newdata[2011]
<ipython-input-8-47fdbec520c1>:74: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2010].iloc[aa] = newdata[2010]
<ipython-input-8-47fdbec520c1>:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2009].iloc[aa] = newdata[2009]
<ipython-input-8-47fdbec520c1>:82: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2008].iloc[aa] = newdata[2008]
<ipython-input-8-47fdbec520c1>:86: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2007].iloc[aa] = newdata[2007]
<ipython-input-8-47fdbec520c1>:90: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2006].iloc[aa] = newdata[2006]
<ipython-input-8-47fdbec520c1>:94: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2005].iloc[aa] = newdata[2005]
<ipython-input-8-47fdbec520c1>:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2021].iloc[aa] = newdata[2021]
<ipython-input-8-47fdbec520c1>:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2020].iloc[aa] = newdata[2020]
<ipython-input-8-47fdbec520c1>:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2019].iloc[aa] = newdata[2019]
<ipython-input-8-47fdbec520c1>:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2018].iloc[aa] = newdata[2018]
<ipython-input-8-47fdbec520c1>:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2017].iloc[aa] = newdata[2017]
<ipython-input-8-47fdbec520c1>:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2016].iloc[aa] = newdata[2016]
<ipython-input-8-47fdbec520c1>:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2015].iloc[aa] = newdata[2015]
<ipython-input-8-47fdbec520c1>:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2014].iloc[aa] = newdata[2014]
<ipython-input-8-47fdbec520c1>:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2013].iloc[aa] = newdata[2013]
<ipython-input-8-47fdbec520c1>:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2012].iloc[aa] = newdata[2012]
<ipython-input-8-47fdbec520c1>:70: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2011].iloc[aa] = newdata[2011]
<ipython-input-8-47fdbec520c1>:74: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2010].iloc[aa] = newdata[2010]
<ipython-input-8-47fdbec520c1>:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2009].iloc[aa] = newdata[2009]
<ipython-input-8-47fdbec520c1>:82: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2008].iloc[aa] = newdata[2008]
<ipython-input-8-47fdbec520c1>:86: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2007].iloc[aa] = newdata[2007]
<ipython-input-8-47fdbec520c1>:90: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2006].iloc[aa] = newdata[2006]
<ipython-input-8-47fdbec520c1>:94: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2005].iloc[aa] = newdata[2005]
<ipython-input-8-47fdbec520c1>:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2021].iloc[aa] = newdata[2021]
<ipython-input-8-47fdbec520c1>:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2020].iloc[aa] = newdata[2020]
<ipython-input-8-47fdbec520c1>:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2018].iloc[aa] = newdata[2018]
<ipython-input-8-47fdbec520c1>:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2017].iloc[aa] = newdata[2017]
<ipython-input-8-47fdbec520c1>:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2015].iloc[aa] = newdata[2015]
<ipython-input-8-47fdbec520c1>:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2014].iloc[aa] = newdata[2014]
<ipython-input-8-47fdbec520c1>:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2013].iloc[aa] = newdata[2013]
<ipython-input-8-47fdbec520c1>:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2012].iloc[aa] = newdata[2012]
<ipython-input-8-47fdbec520c1>:70: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2011].iloc[aa] = newdata[2011]
<ipython-input-8-47fdbec520c1>:74: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2010].iloc[aa] = newdata[2010]
<ipython-input-8-47fdbec520c1>:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2009].iloc[aa] = newdata[2009]
<ipython-input-8-47fdbec520c1>:82: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2008].iloc[aa] = newdata[2008]
<ipython-input-8-47fdbec520c1>:86: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2007].iloc[aa] = newdata[2007]
<ipython-input-8-47fdbec520c1>:94: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2005].iloc[aa] = newdata[2005]
<ipython-input-8-47fdbec520c1>:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2021].iloc[aa] = newdata[2021]
<ipython-input-8-47fdbec520c1>:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2020].iloc[aa] = newdata[2020]
<ipython-input-8-47fdbec520c1>:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv_concat_all[2019].iloc[aa] = newdata[2019]
<ipython-input-8-47fdbec520c1>:42: SettingWithCopyWarning:

In [ ]:
df_csv_concat_all.to_excel("data-"+ sector +"ALLDATA"+".xlsx")
df_csv_concat_all

,Company,Price,Change,EPS,PER,Market Cap.(Million IDR),URL,2022,2021,2020,...,2014,2013,2012,2011,2010,2009,2008,2007,2006,2005
0,ICBP,10.875,"+150 (+1,38%)",339,32.0,"128.572.446,00",https://www.idnfinancials.com/icbp/pt-indofood...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,MYOR,2.640,"+60 (+2,27%)",33,80.0,"60.368.492,00",https://www.idnfinancials.com/myor/pt-mayora-i...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,INDF,6.700,"+175 (+2,61%)",438,15.0,"60.365.459,00",https://www.idnfinancials.com/indf/pt-indofood...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,CMRY,4.380,"-60 (-1,00%)",37,118.0,"34.277.817,00",https://www.idnfinancials.com/cmry/pt-cisarua-...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,MLBI,8.950,"-50 (-1,00%)",97,92.0,"18.752.301,00",https://www.idnfinancials.com/mlbi/pt-multi-bi...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,GOOD,468.000,"-4 (-1,00%)",4,109.0,"16.949.131,00",https://www.idnfinancials.com/good/pt-garudafo...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,PANI,1.175,"+45 (+4,00%)",4,305.0,"16.506.601,00",https://www.idnfinancials.com/pani/pt-pratama-...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,ULTJ,1.470,"+10 (+1,00%)",34,43.0,"15.389.335,00",https://www.idnfinancials.com/ultj/pt-ultra-ja...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,ROTI,1.325,"+30 (+2,00%)",75,18.0,"7.727.877,00",https://www.idnfinancials.com/roti/pt-nippon-i...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,DMND,805.000,"-5 (-0,62%)",29,28.0,"7.622.030,00",https://www.idnfinancials.com/dmnd/pt-diamond-...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,CLEO,525.000,"+5 (+1,00%)",16,33.0,"6.338.800,00",https://www.idnfinancials.com/cleo/pt-sariguna...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,ADES,8.025,"+75 (+1,00%)",408,20.0,"4.882.364,00",https://www.idnfinancials.com/ades/pt-akasha-w...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,DLTA,3.850,"+10 (+0,26%)",227,17.0,"3.146.738,00",https://www.idnfinancials.com/dlta/pt-delta-dj...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,PSGO,140.000,"-1 (-1,00%)",7,19.0,"2.620.150,00",https://www.idnfinancials.com/psgo/pt-palma-se...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,BTEK,50.000,0 (0%),-3,-17.0,"2.313.875,00",https://www.idnfinancials.com/btek/pt-bumi-tek...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,IBOS,262.000,"-2 (-1,00%)",0,535.0,"2.089.810,00",https://www.idnfinancials.com/ibos/pt-indo-bog...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,CAMP,344.000,"-2 (-0,58%)",18,19.0,"2.024.440,00",https://www.idnfinancials.com/camp/pt-campina-...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,KEJU,1.260,"+5 (+0,40%)",76,17.0,"1.897.500,00",https://www.idnfinancials.com/keju/pt-mulia-bo...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,TRGU,212.000,"+2 (+1,00%)",7,31.0,"1.700.318,00",https://www.idnfinancials.com/trgu/pt-cerestar...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,SKLT,2.400,"+70 (+3,00%)",67,36.0,"1.535.515,00",https://www.idnfinancials.com/sklt/pt-sekar-la...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,WINE,438.000,"+107 (+24,00%)",10,42.0,"1.476.950,00",https://www.idnfinancials.com/wine/pt-hatten-b...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,BEER,346.000,"+2 (+1,00%)",3,111.0,"1.392.000,00",https://www.idnfinancials.com/beer/pt-jobubu-j...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,CEKA,2.010,"-10 (-0,50%)",119,17.0,"1.195.950,00",https://www.idnfinancials.com/ceka/pt-wilmar-c...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,BUDI,216.000,"+8 (+4,00%)",14,15.0,"1.007.776,00",https://www.idnfinancials.com/budi/pt-budi-sta...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,HOKI,89.000,"-1 (-1,00%)",0,494.0,"851.642,00",https://www.idnfinancials.com/hoki/pt-buyung-p...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,PMMP,288.000,"+2 (+1,00%)",0,90.0,"682.370,00",https://www.idnfinancials.com/pmmp/pt-panca-mi...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,WMUU,50.000,0 (0%),-1,-71.0,"647.060,00",https://www.idnfinancials.com/wmuu/pt-widodo-m...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,AISA,144.000,"-3 (-2,00%)",-4,-34.0,"536.607,00",https://www.idnfinancials.com/aisa/pt-fks-food...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,SKBM,312.000,"-20 (-6,00%)",29,11.0,"505.189,00",https://www.idnfinancials.com/skbm/pt-sekar-bu...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,CRAB,226.000,"+4 (+1,77%)",2,146.0,"448.500,00",https://www.idnfinancials.com/crab/pt-toba-sur...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
30,NAYZ,163.000,"-4 (-2,45%)",1,148.0,"405.450,00",https://www.idnfinancials.com/nayz/pt-hassana-...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31,GULA,298.000,"+14 (+4,70%)",3,101.0,"333.952,00",https://www.idnfinancials.com/gula/pt-aman-agr...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32,COCO,232.000,"+4 (+1,72%)",5,45.0,"210.008,00",https://www.idnfinancials.com/coco/pt-wahana-i...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
33,TAYS,167.000,"-11 (-6,59%)",9,19.0,"171.432,00",https://www.idnfinancials.com/tays/pt-jaya-swa...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34,MGNA,50.000,0 (0%),-3,-14.0,"170.524,00",https://www.idnfinancials.com/mgna/pt-magna-in...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35,BOBA,144.000,"-1 (-0,69%)",8,18.0,"167.567,00",https://www.idnfinancials.com/boba/pt-formosa-...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36,ALTO,50.000,0 (0%),2,28.0,"109.593,00",https://www.idnfinancials.com/alto/pt-tri-bany...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
37,ENZO,50.000,0 (0%),1,40.0,"108.128,00",https://www.idnfinancials.com/enzo/pt-morenzo-...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
38,PSDN,53.000,"+1 (+2,00%)",-22,-2.0,"77.760,00",https://www.idnfinancials.com/psdn/pt-prasidha...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
39,FOOD,106.000,"+3 (+3,00%)",-19,-5.0,"70.850,00",https://www.idnfinancials.com/food/pt-sentra-f...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
40,NASI,82.000,"-5 (-6,00%)",2,46.0,"62.170,00",https://www.idnfinancials.com/nasi/pt-wahana-i...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41,AMMS,52.000,"-3 (-6,00%)",1,39.0,"58.801,00",https://www.idnfinancials.com/amms/pt-agung-me...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
42,PCAR,50.000,0 (0%),3,17.0,"58.333,00",https://www.idnfinancials.com/pcar/pt-prima-ca...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
43,IKAN,56.000,"+2 (+4,00%)",2,23.0,"48.333,00",https://www.idnfinancials.com/ikan/pt-era-mand...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
44,SOUL,27.000,"+1 (+4,00%)",1.029.119,0.0,"30.310,00",https://www.idnfinancials.com/soul/pt-mitra-ti...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
45,STTP,7.425,0 (0%),320,23.0,0,https://www.idnfinancials.com/sttp/pt-siantar-...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
46,IIKP,50.000,0 (0%),-4,-13.0,0,https://www.idnfinancials.com/iikp/pt-inti-agr...,0,0,0,...,0,0,0,0,0,0,0,0,0,0